# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_imagine:
    resource: .
    type:     imagine

m038KunstkamerBundle:
    resource: "@m038KunstkamerBundle/Controller/"
    type:     annotation
    prefix:   /